config = {  
            "-varprune":[0,int],
            "-recompute":[False,bool],
            "-sort":[False,bool],
            "-no-sos":[False,bool],
            "-no-eos":[False,bool],
            "-write":["./counts",str],
            "-gtmin":[1,int],
            "-gtmax":[5,int],
            "-ndiscount":[False,bool],
            "-wbdiscount":[False,bool],
            "-kndiscount":[True,bool],
            "-ukndiscount":[False,bool],
            "-interpolate":[True,bool],
            "-prune":[0,int],
            "-minprune":[2,int],
        }